### ISSUE TITLE
Any way to install without access to GitHub?

### ISSUE THREAD

**Issue by bschonec** [voxpupuli/puppet-puppetboard#202] opened 2018-03-01 18:47 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## How to reproduce (e.g Puppet code you use)

```puppet
 class { 'puppetboard':
   manage_git => false,
   manage_virtualenv => false,
 }
```

## What are you seeing

Module tries to clone git repository.

## What behaviour did you expect instead

Puppet module voxpupuli-puppetboard is already installed in my modules path.  I don't need it [re]installed as I don't have access to the Internet from the Puppetboard server.

## Any additional information you'd like to impart

'vcsrepo' is trying to git clone the puppetboard repository.  I don't have access to the Internet from this server.

**Comment by tthayer** [comment] 2018-10-08 20:54
@bschonec See this line: https://github.com/voxpupuli/puppet-puppetboard/blob/master/manifests/init.pp#L34

You can pass your local repo address as a class parameter to override the default.

**Comment by rledousa** [comment] 2021-01-12 22:37
+1.  Our production servers do not have access to the internet or Git repos so local repo is not an option.  Option to install via pip3 would be much appreciated.

**Comment by kenyon** [comment] 2021-11-04 06:19
Duplicate of #85. Also, you can specify the URL to your own copy of the puppetboard repo.

**Closed by kenyon** 2021-11-04 06:19 UTC
Labels: question

**Comment by rledousa** [comment] 2021-11-04 23:20
Hi-

We don't have an internal copy of the repo, we use an internal proxy for pip installations, so our pip.conf looks like:

[global]
index-url = https://pypi.company.com/simple

[search]
index = https://pypi.company.com/

Hope that helps
